# Generated by Django 3.0.3 on 2020-02-04 03:59

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='room_code',
            field=models.CharField(default=game.models.Game.random_room_code, max_length=4),
        ),
    ]
