# Generated by Django 3.0.3 on 2020-02-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200203_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_team',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
