# Generated by Django 3.0.3 on 2020-02-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_first_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='first_team',
            new_name='team_turn',
        ),
    ]
