# Generated by Django 3.0.3 on 2020-02-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200219_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
