# Generated by Django 3.0.3 on 2020-02-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_avatar_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='room_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
