# Generated by Django 3.0.3 on 2020-02-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player_room_alerted'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ip',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
