# Generated by Django 3.0.2 on 2020-05-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_clue',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='words_left',
            field=models.IntegerField(default=0),
        ),
    ]
