# Generated by Django 3.0.2 on 2020-06-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20200606_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last_act',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ip',
        ),
    ]
